spring:
  activemq:
    broker-url: tcp://localhost:61616
          #?jms.useAsyncSend=true
    packages:
      trust-all: true
      #trusted:
      #- com.example.activemq
  jms:
    pub-sub-domain: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
topic: workflow
      #?consumer.retroactive=true
server:
  port: 8770

