spring:
  activemq:
    broker-url: tcp://localhost:61616
          #?jms.useAsyncSend=true
    packages:
      trust-all: true
      #trusted:
      #- com.example.activemq
  jms:
    pub-sub-domain: true
  
  # database connection config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  security:    user:      name: admin
      password: password
  resources:
    static-locations:
      file:/Workflow/**/**/**    
  # activiti default configuration
  activiti:
    database-schema-update: true
    db-history-used: true
    check-process-definitions: true
    #process-definition-location-prefix: classpath:/Workflow
    # process-definition-location-suffixes:
    # - **.bpmn
    # - **.bpmn20.xml
    history-level: audit
logging:  level:
    com.example.workflow:
      DEBUG
topic: workflow
      #?consumer.retroactive=true
server:
  port: 8770

